### ISSUE TITLE
Build fail on Mac OS X

### ISSUE THREAD

**Issue by Tigerism** [TitanSnow/ffilupa#2]
I already have python3 and Lua 5.3.5.
```
$ lua
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> 
```

I installed ffilupa through ``pip3 install git+https://github.com/TitanSnow/ffilupa.git``, and I'm getting the ``Required lua lib not found`` error; however, I already have 5.3.5. I uninstalled Lua and installed 5.3.0, then ``pip3 uninstall ffilupa``, and then ``pip3 install git+https://github.com/TitanSnow/ffilupa.git``; however, I still get the error. I also tried the steps with 5.2.0.

I'm not sure what the problem is. I have the correct Lua version as specified in the instructions.

**Comment by TitanSnow** [comment]
ffilupa uses `pkg-config` to find lua library. Could you please try `pkg-config --list-all` and if there's a lua library. The lua development library is needed. On ubuntu for example it's `liblua5.3-dev`. It's not enough to have only `liblua5.3`.

BTW, I have published ffilupa 3.0.0 to PyPI. So you can just `pip install ffilupa` and there's no need to install from git.

**Comment by Tigerism** [comment]
I can't seem to find the Lua development library for macOS on google. How would I install it?

**Comment by TitanSnow** [comment]
```
brew install pkg-config lua
```

**Comment by Tigerism** [comment]
I ran that previously, and my output is:
```
Warning: pkg-config 0.29.2 is already installed and up-to-date
To reinstall 0.29.2, run `brew reinstall pkg-config`
Warning: lua 5.3.5 is already installed and up-to-date
To reinstall 5.3.5, run `brew reinstall lua`
```

I reinstalled ffilupa, and I'm still getting the 'required lib not found' error.

**Comment by TitanSnow** [comment]
May you please check if there's lua in `pkg-config --list-all`. If there's not, the lua you have installed might not from homebrew (homebrew *will* install the development library). Please reinstall it with homebrew.

**Comment by Tigerism** [comment]
It's there. There are multiple listed:

lua-5.1        Lua - An Extensible Extension Language
lua            Lua - An Extensible Extension Language
lua-5.3        Lua - An Extensible Extension Language
lua5.1         Lua - An Extensible Extension Language
lua5.3         Lua - An Extensible Extension Language

**Comment by Tigerism** [comment]
Command: ``pip install git+https://github.com/TitanSnow/ffilupa.git``;
Console: ```
Collecting git+https://github.com/TitanSnow/ffilupa.git
  Cloning https://github.com/TitanSnow/ffilupa.git to /private/var/folders/wm/zl9hlhs54b93wx17f3vw6krr0000gn/T/pip-req-build-q6ta3lid
Requirement already satisfied: cffi~=1.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ffilupa==3.0.0) (1.11.5)
Requirement already satisfied: semantic_version~=2.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from ffilupa==3.0.0) (2.6.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from cffi~=1.10->ffilupa==3.0.0) (2.18)
Installing collected packages: ffilupa
  Running setup.py install for ffilupa ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/wm/zl9hlhs54b93wx17f3vw6krr0000gn/T/pip-req-build-q6ta3lid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wm/zl9hlhs54b93wx17f3vw6krr0000gn/T/pip-record-lweu1gem/install-record.txt --single-version-externally-managed --compile:
    generating build/ffilupa/_lua53.c
    (already up-to-date)
    not modified: 'build/ffilupa/_lua53.c'
    generating build/_ffilupa_embedding_lua53.c
    (already up-to-date)
    not modified: 'build/_ffilupa_embedding_lua53.c'
    running install
    running build
    running build_py
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/metatable.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/exception.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/lualibs.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/compat.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/util.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/protocol.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/runtime.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/py_from_lua.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/py_to_lua.py -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    creating build/lib.macosx-10.9-x86_64-3.6/findlua
    copying findlua/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/findlua
    copying findlua/embedding-template.py -> build/lib.macosx-10.9-x86_64-3.6/findlua
    running egg_info
    creating ffilupa.egg-info
    writing ffilupa.egg-info/PKG-INFO
    writing dependency_links to ffilupa.egg-info/dependency_links.txt
    writing requirements to ffilupa.egg-info/requires.txt
    writing top-level names to ffilupa.egg-info/top_level.txt
    writing manifest file 'ffilupa.egg-info/SOURCES.txt'
    reading manifest file 'ffilupa.egg-info/SOURCES.txt'
    writing manifest file 'ffilupa.egg-info/SOURCES.txt'
    copying ffilupa/lua.json -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    copying ffilupa/version.txt -> build/lib.macosx-10.9-x86_64-3.6/ffilupa
    running build_ext
    building 'ffilupa._lua53' extension
    creating build/temp.macosx-10.9-x86_64-3.6
    creating build/temp.macosx-10.9-x86_64-3.6/build
    creating build/temp.macosx-10.9-x86_64-3.6/build/ffilupa
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -g -I/usr/local/include/lua -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c build/ffilupa/_lua53.c -o build/temp.macosx-10.9-x86_64-3.6/build/ffilupa/_lua53.o
    gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.6/build/ffilupa/_lua53.o -L/usr/local/lib -llua -lm -lpython3.6m -o build/lib.macosx-10.9-x86_64-3.6/ffilupa/_lua53.cpython-36m-darwin.so
    ld: library not found for -lpython3.6m
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/wm/zl9hlhs54b93wx17f3vw6krr0000gn/T/pip-req-build-q6ta3lid/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/wm/zl9hlhs54b93wx17f3vw6krr0000gn/T/pip-record-lweu1gem/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/wm/zl9hlhs54b93wx17f3vw6krr0000gn/T/pip-req-build-q6ta3lid/
```

**Comment by TitanSnow** [comment]
Because you are building from source, the development library of python is also required. You can `brew install python`. I'll put 'wheels' into next release.

**Comment by TitanSnow** [comment]
Fixed in 3.0.1

**Comment by Tigerism** [comment]
Thank you! I will have this library another go.

**Comment by TitanSnow** [comment]
I apologize for leaving this issue open for such a long time. Well, it’s because I don’t have a Mac.

The reason why the build failed is that during installation, ffilupa would try building an embedding library for use python in lua, which is an optional feature and before 3.0.1, it was tuned on by default. It requires to link against the python library, on Linux which is `python3.?m` and is present in the path for compiler to search for. However, on macOS, possibly due to Homebrew’s design, it’s not in a path compiler search for shared libraries by default, so the compilation error happens.
